### ISSUE TITLE
 Add Key Info content

### ISSUE THREAD

**Issue by ashishrajput15** [ashishrajput15/COVID-selfreport#5]
The following content needs to be added.

Helpful Links
HELPLINE NUMBERS (by State)
https://www.mohfw.gov.in/coronvavirushelplinenumber.pdf

Key Information and Resources
Ministry of Health and Family Welfare, Gov. of India
https://www.mohfw.gov.in/
WHO : COVID-19 Home Page
https://www.who.int/emergencies/diseases/novel-coronavirus-2019
CDC
https://www.cdc.gov/coronavirus/2019-ncov/faq.html
COVID-19 Global Tracker
https://coronavirus.thebaselab.com/

**Comment by speedcuber911** [comment]
I will be working on this.
