### ISSUE TITLE
Add Helpline Nos content based on the location.

### ISSUE THREAD

**Issue by ashishrajput15** [ashishrajput15/COVID-selfreport#6]
Helpline number based on the geolocation to be shown. Below which we have to add national helpline numbers.
""
National Helpline Number
1075  |  1800-112-545
Central Helpline Number
+91-11-23978043  |  +91-11-23978046
Central Helpline Email
ncov2019@gmail.com )
"""

Statewise Helpline number:
1 | Andhra Pradesh | 0866-2410978
2 | Arunachal Pradesh | 9536055743
3 | Assam | 6913347770
4 | Bihar | 104
5 | Chhattisgarh | 077122-35091
6 | Goa | 104
7 | Gujarat | 104
8 | Haryana | 8558893911
9 | Himachal Pradesh | 104
10 | Jharkhand | 104
11 | Karnataka | 104
12 | Kerala | 0471-2552056
13 | Madhya Pradesh | 0755-2527177
14 | Maharashtra | 020-26127394
15 | Manipur | 3852411668
16 | Meghalaya | 9366090748
17 | Mizoram | 102
18 | Nagaland | 7005539653
19 | Odisha | 9439994859
20 | Punjab | 104
21 | Rajasthan | 0141-2225624
22 | Sikkim | 104
23 | Tamil Nadu | 044-29510500
24 | Telangana | 104
25 | Tripura | 0381-2315879
26 | Uttarakhand | 104
27 | Uttar Pradesh | 18001805145
28 | West Bengal | 3323412600

**Comment by speedcuber911** [comment]
I will be working on this.

**Comment by speedcuber911** [comment]
Opened a pull request for the same. We need to add a phone no. for Delhi too.

**Comment by speedcuber911** [comment]
Adding phone numbers for: union territories
https://www.mohfw.gov.in/coronvavirushelplinenumber.pdf

**Comment by a1ananth** [comment]
@ashishrajput15 need your feedback on this incl. design. One suggestion I have is making the help-line phone numbers clickable.
